name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image APIs
      run: docker build . --file Dockerfile --tag desafioexecutable:$(date +%s)
    - name: Build the Docker image Blazor Server
      run: docker build . --file DockerfileInterface --tag desafioInterfaceexecutable:$(date +%s)
